# -*- coding: utf-8 -*-
"""AI assignment_1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1HXaDsWBLRxUOOTM9WIDTivR4pmmTqonh

Breadth-First
Uniform-Cost
Depth-First
Depth-Limited
Iterative Deepening

**DFS**
"""

graph={
    'A':['B','C'],
    'B':['D','E'],
    'C':['F'],
    'D': [],
    'E': ['F'],
    'F': []
}

def dfs(graph,start,visited=None):
  if visited is None:
    visited=set()
  visited.add(start)
  print(start,end=" ")
  for next in graph[start]:
    if next not in visited:
      dfs(graph,next,visited)
print("dfs")
dfs(graph,'A')

"""**BFS**"""

from collections import deque
def bfs(graph,start):
  visited=set()
  queue=deque([start])
  visited.add(start)

  while queue:
    node=queue.popleft()
    print(node,end=" ")

    for next in graph[node]:
      if next not in visited:
        visited.add(next)
        queue.append(next)
print("BFS")
bfs(graph,'A')

"""**Uniform cost Search**"""

import heapq

graph_ucs={
    'A':[('B',1),('C',4)],
    'B':[('D',3),('E',1)],
    'C':[('F',2)],
    'D':[],
    'E':[('F',5)],
    'F':[]

}

def ucs(graph,start,goal):
  visited=set()
  queue=[(0,start,[start])] #(cost so far,node,path)
  while queue:
    cost,node,path=heapq.heappop(queue)
    if node in visited:
      continue
    visited.add(node)
    if node==goal:
      print("Path:","->".join(path))
      print("Total Cost:",cost)
      return
    for next,weight in graph_ucs[node]:
        if next not in visited:
          heapq.heappush(queue,(cost+weight,next,path+[next]))
  print("No path found")
print("UCS")
ucs(graph_ucs,'A','F')

"""Depth-Limited"""

def dls(graph,node,goal, limit,path=None):
  if path is None:
    path=[node]
  if node==goal:
    return path
  if limit==0:
    return None
  for next in graph[node]:
    if next not in path:
      result=dls(graph,next,goal,limit-1,path+[next])
      if result is not None:
        return result
  return None
goal ='F'
for limit in [1, 2, 3]:
    print("Depth limit =", limit)
    path = dls(graph, 'A', goal, limit)
    if path:
        print("Path:", " -> ".join(path))
    else:
        print("Goal not found within limit")
    print()

"""**Iterative Deepening**"""

def dls(graph, node, goal, limit, path=None):
    if path is None:
        path = [node]

    if node == goal:
        return path

    if limit == 0:
        return None

    for next in graph[node]:
        if next not in path:
            result = dls(graph, next, goal, limit - 1, path + [next])
            if result is not None:
                return result
    return None

def iddfs(graph, start, goal, max_depth=10):
    for depth in range(max_depth + 1):
        print("Trying depth limit =", depth)
        result = dls(graph, start, goal, depth)
        if result is not None:
            return result
    return None

path = iddfs(graph, 'A', 'F')
if path:
    print("Path:", " -> ".join(path))
    print("Found at depth:", len(path) - 1)
else:
    print("Goal not found")







